logging:
  level:
    ROOT: INFO
    org:
      springframework:
        cloud:
          stream: DEBUG

server:
  port: 8082
  servlet:
    context-path: /api/venda

spring:
  application:
    name: loja-consumidor-service
  profiles:
    active: dev
  h2:
    console:
      enabled: true
      path: /h2-console

  datasource:
    url: jdbc:h2:mem:venda_db2
    username: sa
    password:
    driverClassName: org.h2.Driver
    test-on-borrow: true
    validation-query: SELECT 1
    test-while-idle: true
    time-between-eviction-runs-millis: 90000

  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    database: H2
    show-sql: false
    properties:
      hibernate.format_sql: true
      hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: 'update'

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: 5672
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

  cloud:
    stream:
      bindings:
        vendaChannel:
          destination: venda.exchange
          contentType: application/json
          group: vendas
        vendaCodChannel:
          destination: codvenda.exchange
          contentType: application/json
          group: codvendas

app:



